#!/usr/bin/env bash
name='libreoffice'
release='1'
url='https://documentfoundation.org/libreoffice'
description='Libreoffice binary package.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
version="7.5.4"
source=("https://download.documentfoundation.org/libreoffice/stable/7.5.4/deb/x86_64/LibreOffice_7.5.4_Linux_x86-64_deb.tar.gz")
md5sums=(SKIP)
license=('GPLv3')
depends=()
makedepends=()
group=()
uses=()
unsafe=1
arch=('x86_64')
# find latest version
#
#    wget -O - https://download.documentfoundation.org/libreoffice/stable/ | grep -e "href=\"[0-9]" | \
#        sed "s/.*href=\"//g;s/.\".*//g" | sort -V | tail -n 1
#

package () {
    mkdir -p $DESTDIR
    cd $DESTDIR
    for file in $(ls "$HOME/LibreOffice_7.5.4.2_Linux_x86-64_deb/DEBS/"*.deb) ; do
        echo "Extract: $file"
        ar x "$file"
        tar -xf data.tar.*
        rm -rf control.tar.* debian-binary data.tar.*
    done
    rm -rf $DESTDIR/usr/share/mimeinfo
}
