#!/usr/bin/env bash
name='libreoffice'
release='1'
url='https://documentfoundation.org/libreoffice'
description='Libreoffice binary package.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
version="7.5.4"
source=("https://download.documentfoundation.org/libreoffice/stable/7.5.4/deb/x86_64/LibreOffice_7.5.4_Linux_x86-64_deb.tar.gz")
md5sums=(SKIP)
license=('GPLv3')
depends=()
makedepends=()
group=()
uses=()
arch=('x86_64')
# find latest version
#
#    wget -O - https://download.documentfoundation.org/libreoffice/stable/ | grep -e "href=\"[0-9]" | \
#        sed "s/.*href=\"//g;s/.\".*//g" | sort -V | tail -n 1
#

package () {
    mkdir -p $DESTDIR
    cd $DESTDIR
    for file in $(ls "$HOME/LibreOffice_7.5.4.2_Linux_x86-64_deb/DEBS/"*.deb) ; do
        echo "Extract: $file"
        ar x "$file"
        tar -xf data.tar.*
        rm -rf control.tar.* debian-binary data.tar.*
    done
    # fix symlink
    rm -f $DESTDIR/usr/local/bin/libreoffice7.5
    rm -f $DESTDIR/usr/share/applications/libreoffice7.5-startcenter.desktop
    rm -f $DESTDIR/usr/share/applications/libreoffice7.5-xsltfilter.desktop
    mkdir -p $DESTDIR/usr/bin/
    ln -s ../../opt/libreoffice7.5/program/soffice $DESTDIR/usr/bin/libreoffice7.5
    for prog in base impress draw calc writer math ; do
        if ls $DESTDIR/usr/share/applications/libreoffice7.5-$prog.desktop  ; then
            rm -f $DESTDIR/usr/share/applications/libreoffice7.5-$prog.desktop
            ln -s ../../../opt/libreoffice7.5/share/xdg/$prog.desktop $DESTDIR/usr/share/applications/libreoffice7.5-$prog.desktop
        fi
    done
    rm -rf $DESTDIR/usr/share/mimeinfo
}
